language: java
jdk:
   - oraclejdk8

env:
   - SERVER = test-wildfly

script: mvn verify -P $SERVER

deploy:
   provider: script
   script: mvn deploy -Dmaven.test.skip -s settings.xml
   on:
      branch: develop
